@baseUrl = https://jsonplaceholder.typicode.com
@host= http://apis.imooc.com/api

@iCode = 25CD6C99F4575679

GET {{baseUrl}}/posts HTTP/1.1

###
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "This is a title for test",
  "body": "This is content for test",
  "userId": 1
}
###
GET http://apis.imooc.com/api/banners?icode=25CD6C99F4575679
###

GET {{host}}/ads?icode={{iCode}}&categories_like=cars HTTP/1.1

###
GET {{host}}/products?icode={{iCode}}&categories_like=cars HTTP/1.1

###
GET {{host}}/productVariants?_expand=product&_embed=productVariantImages&productId=1&icode={{iCode}} HTTP/1.1