@baseUrl = https://jsonplaceholder.typicode.com
@host= http://apis.imooc.com/api

@iCode = 25CD6C99F4575679

GET {{baseUrl}}/posts HTTP/1.1

###
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "title": "这是一个测试帖子的标题",
  "body": "这是一个测试帖子的内容",
  "userId": 1
}
###
GET http://apis.imooc.com/api/banners?icode=25CD6C99F4575679
###

GET {{host}}/ads?icode={{iCode}}&categories_like=cars HTTP/1.1

###

GET {{host}}/products?icode={{iCode}}&categories_like=cars HTTP/1.1
